DROP TABLE employee;
CREATE TABLE employee
(
	eno			NUMBER PRIMARY KEY,
	name 		VARCHAR2(20),
	depart		VARCHAR2(20),
	salary		NUMBER,
	hire		DATE
);

DROP SEQUENCE	employee_seq;
CREATE SEQUENCE employee_seq INCREMENT BY 1 START WITH 1000 NOMINVALUE NOMAXVALUE NOCYCLE NOCACHE;
