/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2022-01-14 01:33:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SmartWeb0825/springstudy/nearby/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/NEARBY/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1638260032713L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>NearBy 회원가입 페이지</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/titleImg3.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\" integrity=\"sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\" integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@10\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/join.css\">\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\tfnIdCheck();\r\n");
      out.write("\tfnPwCheck();\r\n");
      out.write("\tfnPw2Check();\r\n");
      out.write("\tfnNameCheck();\r\n");
      out.write("\tfnEmailCheck();\r\n");
      out.write("\tfnPhoneCheck();\r\n");
      out.write("\tfnbirth();\r\n");
      out.write("\tfnAllCheck();\r\n");
      out.write("   \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\t// 아이디 정규식\r\n");
      out.write("\tlet regId = /^[a-zA-Z0-9_-]{4,12}$/;\r\n");
      out.write("\t// 비밀번호 정규식\r\n");
      out.write("\tlet regPw = /^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{8,20}$/;\r\n");
      out.write("\t// 이름 정규식\r\n");
      out.write("\tlet regName = /^[a-zA-Z가-힣]{1,30}$/;\r\n");
      out.write("\t// 이메일 정규식\r\n");
      out.write("\tlet regEmail = /^[0-9a-zA-Z-_]+@[a-zA-Z0-9]+([.][a-zA-Z]{2,}){1,2}/;\r\n");
      out.write("\t// 핸드폰 번호 정규식\r\n");
      out.write("\tlet regPhone = /^((01[1|6|7|8|9])[1-9]+[0-9]{6,7})|(010[1-9][0-9]{7})$/;\r\n");
      out.write("\r\n");
      out.write("\tlet id_result = false;\r\n");
      out.write("\tlet pw_result = false;\r\n");
      out.write("\tlet pw2_result = false;\r\n");
      out.write("\tlet name_result = false;\r\n");
      out.write("\tlet email_result = false;\r\n");
      out.write("\tlet authCodePass = false;\r\n");
      out.write("\tlet birthday_result = false;\r\n");
      out.write("\tlet phone_result = false;\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t/* 아이디 */\r\n");
      out.write("\tfunction fnIdCheck() {\r\n");
      out.write("\t    // 1차 정규식 체크\r\n");
      out.write("\t    $('#id').on('keyup blur', function(){\r\n");
      out.write("\t    \tif($('#id').val() == ''){\r\n");
      out.write("\t\t\t\t$('.idCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.idCheckFalse').css('display', 'block');\r\n");
      out.write("\t\t\t\t$('#id_check_msg').text('필수 정보 입니다.')\r\n");
      out.write("\t\t\t\t\t\t\t\t  .removeClass('pass_msg')\r\n");
      out.write("\t\t\t\t\t\t\t\t  .addClass('error_msg');\r\n");
      out.write("\t\t\t\tid_result = false;\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}else if(regId.test($(this).val()) == false ){\r\n");
      out.write("\t\t\t\t$('.idCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.idCheckFalse').css('display', 'block');\r\n");
      out.write("\t            $('#id_check_msg').text('아이디는 4~ 12자의 영문 대소문자/숫자 사용 가능합니다.')\r\n");
      out.write("\t\t\t\t\t\t\t\t  .addClass('error_msg')\r\n");
      out.write("\t\t\t\t\t\t\t\t  .removeClass('pass_msg');\r\n");
      out.write("\t            id_result = false;\r\n");
      out.write("\t            return;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        // 중복 체크\r\n");
      out.write("\t        $.ajax({\r\n");
      out.write("\t            url: '/nearby/member/idCheck',\r\n");
      out.write("\t            type: 'post',\r\n");
      out.write("\t            data: 'id=' + $(this).val(),\r\n");
      out.write("\t            dataType: 'json',\r\n");
      out.write("\t            success: function(map){\r\n");
      out.write("\t                if(map.result == null ){\r\n");
      out.write("\t\t\t\t\t\t$('.idCheckTrue').css('display', 'block');\r\n");
      out.write("\t\t\t\t\t\t$('.idCheckFalse').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t$('#id_check_msg').text('');\r\n");
      out.write("\t                    id_result = true;\r\n");
      out.write("\t                }else {\r\n");
      out.write("\t\t\t\t\t\t$('.idCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t$('.idCheckFalse').css('display', 'block');\r\n");
      out.write("\t                    $('#id_check_msg').text('사용 중인 아이디 입니다.')\r\n");
      out.write("\t                                      .removeClass('pass_msg')\r\n");
      out.write("\t                                      .addClass('error_msg');\r\n");
      out.write("\t                    id_result = false;\r\n");
      out.write("\t                    return;\r\n");
      out.write("\t                }\r\n");
      out.write("\t            },\r\n");
      out.write("\t            error: function(xhr){\r\n");
      out.write("\t            \tconsole.log(xhr.responseText);\r\n");
      out.write("\t\t\t\t\t$('.idCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t$('.idCheckFalse').css('display', 'block');\r\n");
      out.write("\t                $('#id_check_msg').text('사용할 수 없는 아이디 입니다.')\r\n");
      out.write("\t                                  .removeClass('pass_msg')\r\n");
      out.write("\t                                  .addClass('error_msg');\r\n");
      out.write("\t                id_result = false;\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }); // AJAX\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("\t} // end fnIdCheck\r\n");
      out.write("\r\n");
      out.write("\t/* 비밀번호 */\r\n");
      out.write("\tfunction fnPwCheck(){\r\n");
      out.write("\t    $('#pw').on('keyup blur', function(){\r\n");
      out.write("\t        if($('#pw').val() == ''){\r\n");
      out.write("\t\t\t\t$('.pwCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.pwCheckFalse').css('display', 'block');\r\n");
      out.write("\t            $('#pw_check_msg').text('필수 정보 입니다.')\r\n");
      out.write("\t                              .removeClass('pass_msg')\r\n");
      out.write("\t                              .addClass('error_msg');\r\n");
      out.write("\t            pw_result = false;\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t        }else if(regPw.test($(this).val()) == false){\r\n");
      out.write("\t\t\t\t$('.pwCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.pwCheckFalse').css('display', 'block');\r\n");
      out.write("\t            $('#pw_check_msg').text('비밀번호는 8~20자의 영문 대/소문자, 숫자, 특수문자 등 3종류 이상으로 조합해주세요')\r\n");
      out.write("\t                              .removeClass('pass_msg')                  \r\n");
      out.write("\t                              .addClass('error_msg');\r\n");
      out.write("\t            pw_result = false;\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t\t\t\t$('.pwCheckTrue').css('display', 'block');\r\n");
      out.write("\t\t\t\t$('.pwCheckFalse').css('display', 'none');\r\n");
      out.write("\t            $('#pw_check_msg').text('');\r\n");
      out.write("\t            pw_result = true;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}// end fnPwCheck\r\n");
      out.write("\r\n");
      out.write("\t/* 비밀번호 재확인 */\r\n");
      out.write("\tfunction fnPw2Check(){\r\n");
      out.write("\t    $('#pw2').on('keyup blur', function(){\r\n");
      out.write("\t        if($('#pw').val() != $('#pw2').val() ){\r\n");
      out.write("\t\t\t\t$('.pw2CheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.pw2CheckFalse').css('display', 'block');\r\n");
      out.write("\t            $('#pw2_check_msg').text('비밀번호를 확인 해주세요.')\r\n");
      out.write("\t                               .removeClass('pass_msg')\r\n");
      out.write("\t                               .addClass('error_msg');\r\n");
      out.write("\t            pw2_result = false;\r\n");
      out.write("\t        }else if($('#pw2').val() == ''){\r\n");
      out.write("\t\t\t\t$('.pw2CheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.pw2CheckFalse').css('display', 'block');\r\n");
      out.write("\t            $('#pw2_check_msg').text('필수 정보 입니다.')\r\n");
      out.write("\t                               .removeClass('pass_msg')\r\n");
      out.write("\t                               .addClass('error_msg');\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t\t\t\t$('.pw2CheckTrue').css('display', 'block');\r\n");
      out.write("\t\t\t\t$('.pw2CheckFalse').css('display', 'none');\r\n");
      out.write("\t            $('#pw2_check_msg').text('');\r\n");
      out.write("\t            pw2_result = true;\r\n");
      out.write("\t        }\r\n");
      out.write("\r\n");
      out.write("\t    })\r\n");
      out.write("\t}// end fnPw2Check\r\n");
      out.write("\r\n");
      out.write("\t/* 이름 */\r\n");
      out.write("\tfunction fnNameCheck(){\r\n");
      out.write("\t    $('#name').on('keyup blur', function(){\r\n");
      out.write("\t       if($('#name').val() == ''){\r\n");
      out.write("\t\t\t   $('.nameCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t   $('.nameCheckFalse').css('display', 'block');\r\n");
      out.write("\t           $('#name_check_msg').text('필수 정보 입니다.')\r\n");
      out.write("\t                               .removeClass('pass_msg')\r\n");
      out.write("\t                               .addClass('error_msg');\r\n");
      out.write("\t            name_result = false;\r\n");
      out.write("\t       }else if(regName.test($(this).val()) == false){\r\n");
      out.write("\t\t\t   $('.nameCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t   $('.nameCheckFalse').css('display', 'block');\r\n");
      out.write("\t           $('#name_check_msg').text('정말 당신의 이름이 맞습니까 ?')\r\n");
      out.write("\t                               .removeClass('pass_msg')\r\n");
      out.write("\t                               .addClass('error_msg');\r\n");
      out.write("\t        \tname_result = false;\r\n");
      out.write("\t       }else{\r\n");
      out.write("\t\t\t\t$('.nameCheckTrue').css('display', 'block');\r\n");
      out.write("\t\t\t\t$('.nameCheckFalse').css('display', 'none');\r\n");
      out.write("\t            $('#name_check_msg').text('');\r\n");
      out.write("\t            name_result = true;\r\n");
      out.write("\t       }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}// end fnNameChekc\r\n");
      out.write("\r\n");
      out.write("\t/* 이메일 */\r\n");
      out.write("\tfunction fnEmailCheck(){\r\n");
      out.write("\t    $('#email').on('keyup blur', function(){\r\n");
      out.write("\t        if(regEmail.test($(this).val()) == false){\r\n");
      out.write("\t\t\t\t$('#email').css('width', '450px');\r\n");
      out.write("\t            $('#authCode_btn').css('display', 'none');\r\n");
      out.write("\t            $('#emailCheck_btn').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.verifyCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.emailCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.emailCheckFalse').css('display', 'block');\r\n");
      out.write("\t            $('#email_check_msg').text('이메일을 다시 확인 해주세요.')\r\n");
      out.write("\t                                 .removeClass('pass_msg')\r\n");
      out.write("\t                                 .addClass('error_msg');\r\n");
      out.write("\t            email_result = false;\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t\t\t\t$('.emailCheckFalse').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('#email').css('width', '337.5px');\r\n");
      out.write("\t\t\t\t$('#authCode').css('width', '337.5px');\r\n");
      out.write("\t            $('#emailCheck_btn').css('display', 'inline-block');\r\n");
      out.write("\t            $('#email_check_msg').text('')\r\n");
      out.write("\t            email_result = true;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\t\r\n");
      out.write("\t    \t// 이메일 중복 확인\r\n");
      out.write("\t    \t$('#emailCheck_btn').click(function(){\r\n");
      out.write("\t    \t\t$.ajax({\r\n");
      out.write("\t    \t\t\turl: '/nearby/member/selectByEmail',\r\n");
      out.write("\t    \t\t\ttype: 'post',\r\n");
      out.write("\t    \t\t\tdata: 'email=' + $('#email').val(),\r\n");
      out.write("\t    \t\t\tdataType: 'json',\r\n");
      out.write("\t    \t\t\tsuccess: function(map){\r\n");
      out.write("\t\t\t\t\t\tif(map.result == null){\r\n");
      out.write("\t\t\t\t\t\t\t$('#email_check_msg').text('가입 가능한 이메일 입니다.')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t .removeClass('error_msg')\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t .addClass('.pass_msg');\r\n");
      out.write("\t\t\t\t\t\t\t$('#emailCheck_btn').css('display', 'none');\r\n");
      out.write("\t\t\t\t\t\t\t$('#authCode_btn').css('display', 'inline-block');\r\n");
      out.write("\t\t\t\t\t\t\temail_result = true;\r\n");
      out.write("\t\t\t\t\t\t}else if(map.result.email == $('#email').val()){\r\n");
      out.write("\t\t\t\t\t\t\t$('#email_check_msg').text('');\r\n");
      out.write("\t\t\t\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\t\t\t\ttitle: '동일한 이메일이 존재 합니다.',\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\temail_result = false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror : function(xhr){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr.responseText);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t    \t\t});\r\n");
      out.write("\t    \t});\r\n");
      out.write("\t    \r\n");
      out.write("\t        // 인증코드 전송 버튼\r\n");
      out.write("\t        $('#authCode_btn').click(function(){\r\n");
      out.write("\t        \tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'info',\r\n");
      out.write("\t\t\t\t\ttimer: 3000,\r\n");
      out.write("\t\t\t\t\ttitle: '인증 코드 전송 중..',\r\n");
      out.write("  \t\t\t\t\tbutton: false\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('#email').css('width', '450px');\r\n");
      out.write("\t\t\t\t$('.emailCheckTrue').css('display', 'block');\r\n");
      out.write("\t\t\t\t$('#authCode_btn').css('display', 'none');\r\n");
      out.write("\t\t\t \t$('#authCode_box').css('display', 'inline-block');\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: '/nearby/member/sendAuthCode',\r\n");
      out.write("\t\t\t\t\ttype: 'post',\r\n");
      out.write("\t\t\t\t\tdata: 'email=' + $('#email').val(),\r\n");
      out.write("\t\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\t\t\tsuccess: function(map){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(map.authCode);\r\n");
      out.write("\t\t\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t\t\ticon: 'success',\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '인증코드 발송 되었습니다.',\r\n");
      out.write("\t\t\t\t\t\t\ttext: '해당 이메일로 인증코드가 발송 되었습니다.',\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\tfnVerifyAuthCode(map.authCode);\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(xhr){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr.responseText);\r\n");
      out.write("\t\t            \tconsole.log('서버오류');\r\n");
      out.write("\t\t\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\t\t\ttitle: '인증코드 발송 실패.',\r\n");
      out.write("\t\t\t\t\t\t\ttext: '이메일을 다시 확인 해주세요.',\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}); // AJAX          \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t}// end fnEmailCheck\r\n");
      out.write("\r\n");
      out.write("\t/* 인증코드 검증 */\r\n");
      out.write("\tfunction fnVerifyAuthCode(authCode){\r\n");
      out.write("\t\t$('#verify_btn').click(function(){\r\n");
      out.write("\t\t\tif($('#authCode').val() == authCode){\r\n");
      out.write("\t\t\t\t$('.verifyCheckTrue').css('display', 'block');\r\n");
      out.write("\t\t\t\t$('.verifyCheckFalse').css('display', 'none');\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'success',\r\n");
      out.write("\t\t\t\t\ttitle: '성공',\r\n");
      out.write("\t\t\t\t\ttext: '인증 완료 !',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tauthCodePass = true;\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$('.verifyCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '인증 실패.',\r\n");
      out.write("\t\t\t\t\ttext: '인증코드를 다시 확인해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tauthCodePass = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}// fnVerifyAuthCode\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t/* 휴대폰 번호 */\r\n");
      out.write("\tfunction fnPhoneCheck(){\r\n");
      out.write("\t    $('#phone').on('keyup blur', function(){\r\n");
      out.write("\t        if(regPhone.test($(this).val()) == false ){\r\n");
      out.write("\t\t\t\t$('.telCheckTrue').css('display', 'none');\r\n");
      out.write("\t\t\t\t$('.telCheckFalse').css('display', 'block');\r\n");
      out.write("\t            $('#phone_check_msg').text('휴대폰 번호를 정확히 입력 해주세요.')\r\n");
      out.write("\t                             \t .removeClass('pass_msg')\r\n");
      out.write("\t                                 .addClass('error_msg');\r\n");
      out.write("\t            phone_result = false;\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t\t\t\t$('.telCheckTrue').css('display', 'block');\r\n");
      out.write("\t\t\t\t$('.telCheckFalse').css('display', 'none');\r\n");
      out.write("\t            $('#phone_check_msg').text('');\r\n");
      out.write("\t            phone_result = true;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\r\n");
      out.write("\t}// end fnPhoneCheck\r\n");
      out.write("\r\n");
      out.write("\t/* 생년월일 */\r\n");
      out.write("\tfunction fnbirth(){\r\n");
      out.write("\t    let year = '';\r\n");
      out.write("\t    year +=  '<option value=\"\">년</option>';\r\n");
      out.write("\t    for(let i=2007; i>=1907; i--){\r\n");
      out.write("\t        year += '<option value=\"'+i+'\">'+i+'</option>';\r\n");
      out.write("\t    }\r\n");
      out.write("\t     $('#year').html(year);\r\n");
      out.write("\t    \r\n");
      out.write("\t    let month = '';\r\n");
      out.write("\t    month +=  '<option value=\"\">월</option>';\r\n");
      out.write("\t    for(let i=1; i<=9; i++){\r\n");
      out.write("\t\t    month += '<option value=\"'+'0'+i+'\">'+'0'+i+'</option>';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfor(let i=10; i<=12; i++){\r\n");
      out.write("\t\t    month += '<option value=\"'+i+'\">'+i+'</option>';\r\n");
      out.write("\t\t}\r\n");
      out.write("\t     $('#month').html(month);\r\n");
      out.write("\t     \r\n");
      out.write("\t     let day ='';\r\n");
      out.write("\t     day += '<option value=\"\">일</option>';\r\n");
      out.write("\t      for(let i=1; i<=9; i++){\r\n");
      out.write("\t\t     day += '<option value=\"'+'0'+i+'\">'+'0'+i+'</option>';\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t for(let i=10; i<=31; i++){\r\n");
      out.write("\t\t     day += '<option value=\"'+i+'\">'+i+'</option>';\r\n");
      out.write("\t\t }\r\n");
      out.write("\t      $('#day').html(day);\r\n");
      out.write("\t} // end fnPhoneCheck\r\n");
      out.write("\r\n");
      out.write("\t/*\r\n");
      out.write("\t    최종 서브밋 \r\n");
      out.write("\t*/\r\n");
      out.write("\r\n");
      out.write("\tfunction fnAllCheck(){\r\n");
      out.write("\t    $('#join_form').on('submit', function(event){\r\n");
      out.write("\t       if( id_result == false){\r\n");
      out.write("\t           event.preventDefault();\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 입력입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '아이디를 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t           return false;\r\n");
      out.write("\t       }else if( pw_result == false ){\r\n");
      out.write("\t           event.preventDefault();\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 입력입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '비밀번호를 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t           return false;\r\n");
      out.write("\t       }else if( pw2_result == false ){\r\n");
      out.write("\t           event.preventDefault();\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 입력입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '비밀번호를 다시 확인 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t           return false;\r\n");
      out.write("\t       }else if( name_result == false ){\r\n");
      out.write("\t            event.preventDefault();\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 입력입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '이름을 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        }else if( email_result == false ){\r\n");
      out.write("\t            event.preventDefault();\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 입력입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '이메일 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        }else if( authCodePass == false ){\r\n");
      out.write("\t            event.preventDefault();\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '이메일 인증을 받아야 합니다.',\r\n");
      out.write("\t\t\t\t\ttext: '이메일 인증이 필요 합니다.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        }else if( $('#year').val() == ''){\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 정보 입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '생년월일을 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if($('#month').val() == ''){\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 정보 입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '생년월일을 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if($('#day').val() == '' ){\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 정보 입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '생년월일을 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}else if( phone_result == false ){\r\n");
      out.write("\t            event.preventDefault();\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'error',\r\n");
      out.write("\t\t\t\t\ttitle: '필수 정보 입니다.',\r\n");
      out.write("\t\t\t\t\ttext: '휴대폰 번호를 입력 해주세요.',\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t            return false;\r\n");
      out.write("\t        }else{\r\n");
      out.write("\t            return true;\r\n");
      out.write("\t        }\r\n");
      out.write("\t    });\r\n");
      out.write("\t}// end fnAllCheck\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"head\">\r\n");
      out.write("            <h1 class=\"title\"><a href=\"/nearby/\">NearBy</a></h1>\r\n");
      out.write("        </div>\r\n");
      out.write(" \r\n");
      out.write("        <div class=\"join_form\">\r\n");
      out.write("    \r\n");
      out.write("            <form action=\"/nearby/member/insertMember\" method=\"post\" id=\"join_form\">\r\n");
      out.write("                \r\n");
      out.write("                <!-- 아이디 --> \r\n");
      out.write("                <div class=\"input_box\">\r\n");
      out.write("                    <label for=\"id\">아이디</label>\r\n");
      out.write("                        <input type=\"text\" id=\"id\" name=\"id\">\r\n");
      out.write("                        <span class=\"icon\"><i class=\"fas fa-check idCheckTrue\"></i><i class=\"fas fa-times idCheckFalse\"></i></span>\r\n");
      out.write("                    <span id=\"id_check_msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 비밀번호 -->\r\n");
      out.write("                <div class=\"input_box\">\r\n");
      out.write("                    <label for=\"pw\">비밀번호</label>\r\n");
      out.write("                        <input type=\"password\" id=\"pw\" name=\"pw\">\r\n");
      out.write("                    \t<span class=\"icon\"><i class=\"fas fa-check pwCheckTrue\"></i><i class=\"fas fa-times pwCheckFalse\"></i></span>\r\n");
      out.write("                    <span id=\"pw_check_msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 비밀번호 확인 -->\r\n");
      out.write("                <div class=\"input_box\">\r\n");
      out.write("                    <label for=\"pw2\">비밀번호 재확인</label>\r\n");
      out.write("                        <input type=\"password\" id=\"pw2\" >\r\n");
      out.write("                    \t<span class=\"icon\"><i class=\"fas fa-check pw2CheckTrue\"></i><i class=\"fas fa-times pw2CheckFalse\"></i></span>\r\n");
      out.write("                    <span id=\"pw2_check_msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 이름 -->\r\n");
      out.write("                <div class=\"input_box\">\r\n");
      out.write("                    <label for=\"name\">이름</label>\r\n");
      out.write("                        <input type=\"text\" id=\"name\" name=\"name\">\r\n");
      out.write("                    \t<span class=\"icon\"><i class=\"fas fa-check nameCheckTrue\"></i><i class=\"fas fa-times nameCheckFalse\"></i></span>\r\n");
      out.write("                    <span id=\"name_check_msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 이메일 -->\r\n");
      out.write("                <div class=\"email_box\">\r\n");
      out.write("\r\n");
      out.write("                    <!-- 이메일 -->\r\n");
      out.write("                    <label for=\"email\">이메일</label>\r\n");
      out.write("                        <input type=\"text\" id=\"email\" name=\"email\">\r\n");
      out.write("                        <input type=\"button\" value=\"이메일 확인\" id=\"emailCheck_btn\">\r\n");
      out.write("                    \t<span class=\"icon\"><i class=\"fas fa-check emailCheckTrue\"></i><i class=\"fas fa-times emailCheckFalse\"></i></span>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 인증코드 발송 버튼-->\r\n");
      out.write("                    <input type=\"button\" value=\"인증번호받기\" id=\"authCode_btn\">\r\n");
      out.write("                    <span id=\"email_check_msg\"></span>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 인증코드 입력 칸 -->\r\n");
      out.write("                    <div id=\"authCode_box\">\r\n");
      out.write("                        <input type=\"text\" name=\"authCode\" id=\"authCode\">\r\n");
      out.write("                        <input type=\"button\" value=\"인증하기\" id=\"verify_btn\">\r\n");
      out.write("                    \t<span class=\"icon\"><i class=\"fas fa-check verifyCheckTrue\"></i><i class=\"fas fa-times verifyCheckFalse\"></i></span>\r\n");
      out.write("                  <span id=\"verify_msg\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 번호 -->\r\n");
      out.write("                <div class=\"tel_box\">\r\n");
      out.write("                    <label for=\"phone\">번호</label>\r\n");
      out.write("                        <input type=\"text\" id=\"phone\" name=\"phone\" placeholder=\"- 표시 없이 입력해주세요\">\r\n");
      out.write("                    \t<span class=\"icon\"><i class=\"fas fa-check telCheckTrue\"></i><i class=\"fas fa-times telCheckFalse\"></i></span>\r\n");
      out.write("                    <span id=\"phone_check_msg\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 생년월일 -->\r\n");
      out.write("                <div class=\"birth_box\">\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 년도 -->\r\n");
      out.write("                    <label for=\"birthday\">생년월일</label>\r\n");
      out.write("                  <select id=\"year\" name=\"year\"></select>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 월 -->\r\n");
      out.write("                  <select id=\"month\" name=\"month\"></select>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 일 -->\r\n");
      out.write("                  <select id=\"day\" name=\"day\"></select>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- 성별 -->\r\n");
      out.write("                <div class=\"gender_box\">\r\n");
      out.write("                    <p id=\"gender_box\">성별</p>\r\n");
      out.write("                    <!-- 선택 안 함 -->\r\n");
      out.write("                    <input type=\"radio\" name=\"gender\" value=\"n\" id=\"n\" checked>\r\n");
      out.write("                    <label id=\"n\"  for=\"n\">선택안함</label>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 남성 -->\r\n");
      out.write("                    <input type=\"radio\" name=\"gender\" value=\"m\" id=\"male\">\r\n");
      out.write("                    <label id=\"m\"  for=\"male\">남성</label>\r\n");
      out.write("   \r\n");
      out.write("                    <!-- 여성 -->\r\n");
      out.write("                    <input type=\"radio\" name=\"gender\" value=\"f\" id=\"female\">\r\n");
      out.write("                    <label id=\"f\" for=\"female\">여성</label>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"join_btn_wrap\" id=\"join_btn_wrap\">\r\n");
      out.write("                    <button class=\"btn btn-primary\">회원가입</button>                 \r\n");
      out.write("                </div>                \r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"text-align: center;\">\r\n");
      out.write("           <a href=\"/nearby/member/serviceTerms\" id=\"pol\">NearBy 서비스 이용 약관</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
