/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.60
 * Generated at: 2022-01-14 05:21:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class selectView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("f:contains", org.apache.taglibs.standard.functions.Functions.class, "contains", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/SmartWeb0825/springstudy/nearby/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/NEARBY/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1638260032713L));
    _jspx_dependants.put("jar:file:/C:/SmartWeb0825/springstudy/nearby/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/NEARBY/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/SmartWeb0825/springstudy/nearby/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/NEARBY/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>NearBy</title>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/titleImg3.png\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\" integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\" integrity=\"sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@10\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/board/boardFindView.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/selectViewReply.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@10\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("   .board_icon{\r\n");
      out.write("       margin-left: 25px;\r\n");
      out.write("\t   color: gray;\r\n");
      out.write("\t   width: 35px;\r\n");
      out.write("\t   line-height: 32px;\r\n");
      out.write("\t   cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("   .like   { color: #fe4662; cursor: pointer;  }\r\n");
      out.write("   .unlike { color: gray; cursor: pointer;     }\r\n");
      out.write("   \t.pointer {\r\n");
      out.write("   \t\tcursor: pointer;\r\n");
      out.write("   \t} \r\n");
      out.write("   \t.textarea {\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\tmargin: 0 -10px;\r\n");
      out.write("\t\tbackground-color: rgba(255, 250, 250, 0.8);\r\n");
      out.write("\t\twidth: 500px;\r\n");
      out.write("\t\tpadding: 10px 6px 20px 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  /* sweet alert */\r\n");
      out.write("  .swal2-popup { padding: 0.5em; }\r\n");
      out.write("  .swal2-icon {\r\n");
      out.write("  \twidth: 4.5em;\r\n");
      out.write("  \theight: 4.5em;\r\n");
      out.write("  }\r\n");
      out.write("   .swal2-styled { margin:  0.5em; }\r\n");
      out.write("   .swal2-styled.swal2-confirm { width: 100px; background-color: #d4d4d4;  }\r\n");
      out.write("   .swal2-styled.swal2-cancel {width: 100px;}\r\n");
      out.write("   .swal2-icon.swal2-warning { color: pink; border-color: pink;}\r\n");
      out.write("   .swal2-header{ height: 100px; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tfnSendBno();     // 로그인 유저의 게시글 좋아요 한 유무 \r\n");
      out.write("\t\tfnReplyList();\t // 게시글 댓글 리스트\r\n");
      out.write("\t\tfnInsertReply(); // 댓글 삽입\r\n");
      out.write("\t\tfnChangePage();  // 페이징\r\n");
      out.write("\t\tfnShowUpdateBtn();\r\n");
      out.write("\t\tfnUpdateReply(); // 댓글 수정\r\n");
      out.write("\t\tfnDeleteReply(); // 댓글 삭제\r\n");
      out.write("\r\n");
      out.write("\t    var txtArea = $(\".content_height\");\r\n");
      out.write("\t    if (txtArea) {\r\n");
      out.write("\t        txtArea.each(function(){\r\n");
      out.write("\t            $(this).height(this.scrollHeight);\r\n");
      out.write("\t        });\r\n");
      out.write("\t    }\r\n");
      out.write("\t    \r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tfunction fnSetting(){\r\n");
      out.write("\t\t$('.delete_update_form').toggleClass('b_see b_no');\r\n");
      out.write("\t\t$('.delete_form').toggleClass('b_see b_no');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fnDelete(){\r\n");
      out.write("\t\t Swal.fire({\r\n");
      out.write("\t\t\t\ttext: '게시글을 삭제하시겠습니까?',\r\n");
      out.write("\t\t        icon: 'warning',\r\n");
      out.write("\t\t        showCancelButton: true,\r\n");
      out.write("\t\t        closeOnClickOutside: false,\r\n");
      out.write("\t\t        confirmButtonColor: '#D4D4D4',  // confirm\r\n");
      out.write("\t\t        cancelButtonColor: '#D4D4D4',   // cancel\r\n");
      out.write("\t\t        confirmButtonText: '삭제',\r\n");
      out.write("\t\t        cancelButtonText: '취소'\t\r\n");
      out.write("\t\t     }).then((result) => {\r\n");
      out.write("\t             if (result.isConfirmed) {\r\n");
      out.write("\t            \t\tlocation.href= '/nearby/board/deleteBoard?bNo='+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t             }\r\n");
      out.write("\t\t     })    \r\n");
      out.write("\t   }\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fnAdminDelete(i){\r\n");
      out.write("\t\tif( confirm('게시글 번호 '+i+'를 삭제하시겠습니까?') ){\r\n");
      out.write(" \t\t\t$.ajax({\r\n");
      out.write(" \t\t\t\turl : '/nearby/admin/adminBoardDelete',\r\n");
      out.write(" \t\t\t\ttype: \"get\",\r\n");
      out.write(" \t\t\t\tdata : \"bNo=\"+i,\r\n");
      out.write(" \t\t\t\tdataType: 'json',\r\n");
      out.write(" \t\t\t\tcontentType:'application/json',\r\n");
      out.write(" \t\t\t\tsuccess: function(map){\r\n");
      out.write(" \t\t\t\t\t if(map.result.result > 0){\r\n");
      out.write(" \t\t\t\t\t\tlocation.href= \"/nearby/board/boardList\";\r\n");
      out.write(" \t\t\t\t\t } else {\r\n");
      out.write(" \t\t\t\t\t }\r\n");
      out.write(" \t\t\t\t\t}, \r\n");
      out.write(" \t\t\t\terror: function(){\r\n");
      out.write(" \t\t\t\t//\talert(\"ajax에러입니다\")\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t})\r\n");
      out.write(" \t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fnUpdate(){\r\n");
      out.write("\t/* \tif(confirm('게시글을 수정하시겠습니까?') )\r\n");
      out.write("\t\t\tlocation.href= '/board/updateBoardPage?bNo='+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; */\r\n");
      out.write("\t\t Swal.fire({\r\n");
      out.write("\t\t\ttext: '게시글을 수정하시겠습니까?',\r\n");
      out.write("\t        icon: 'warning',\r\n");
      out.write("\t        showCancelButton: true,\r\n");
      out.write("\t        closeOnClickOutside: false,\r\n");
      out.write("\t        confirmButtonColor: '#D4D4D4',  // confirm\r\n");
      out.write("\t        cancelButtonColor: '#D4D4D4',   // cancel\r\n");
      out.write("\t        confirmButtonText: '수정',\r\n");
      out.write("\t        cancelButtonText: '취소'\t\r\n");
      out.write("\t     }).then((result) => {\r\n");
      out.write("             if (result.isConfirmed) {\r\n");
      out.write("            \t location.href= '/nearby/board/updateBoardPage?bNo='+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("; \r\n");
      out.write("             }\r\n");
      out.write("\t     })    \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("    function fnSendBno(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.each($('.output_reply_table'), function(i, replyTable) {\t\r\n");
      out.write(" \t\tlet bNo = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write(" \t\t\t      url: '/nearby/board/boardBnoList',\r\n");
      out.write("\t\t\t      type: 'get',\r\n");
      out.write("\t\t\t      data: \"bNo=\" + bNo,\r\n");
      out.write("\t\t\t      dataType: 'json',\r\n");
      out.write(" \t\t\t      success: function(map) {\r\n");
      out.write("\t\t\t    \t    if( map.count == 1 ){\r\n");
      out.write("\t\t    \t    \t \t$(\"#like\"+bNo).addClass('like');\r\n");
      out.write("\t\t\t    \t    } else if (map.count == 0) {\r\n");
      out.write("\t\t\t    \t    \t$(\"#like\"+bNo).removeClass('like');\r\n");
      out.write("\t\t\t    \t    }\r\n");
      out.write("\t\t\t      },\r\n");
      out.write("\t\t\t      error: function() {\r\n");
      out.write(" \t\t\t      }\r\n");
      out.write(" \t\t\t   }) // End ajax\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t}); // each\r\n");
      out.write(" \t} //  fnSendBno()\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction fnLike(i){\r\n");
      out.write("\t       let likeBtn = $('.like_btn');\r\n");
      out.write("\t       let bNo = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t          \r\n");
      out.write("\t          if( $(\"#\"+i).find('i').hasClass('like') == false )  {\r\n");
      out.write("\t            \t$(\"#\"+i).find('i').addClass('like');\r\n");
      out.write("\t\t            $.ajax({\r\n");
      out.write("\t\t \t\t\t\turl : '/nearby/board/likes',\r\n");
      out.write("\t\t \t\t\t\ttype: 'post',\r\n");
      out.write("\t\t\t\t\t\tdata: \"bNo=\"+i, \r\n");
      out.write("\t\t\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t \t\t\t\tsuccess: function(board){\r\n");
      out.write("  \t\t\t  \t\t\t   $( '#like_count'+bNo ).text(board.likes);\r\n");
      out.write("  \t\t\t  \t\t\t   location.href=\"/nearby/board/selectBoard?bNo=\"+bNo;\r\n");
      out.write("\t\t \t\t\t\t\t\r\n");
      out.write("\t\t \t\t\t\t},\r\n");
      out.write("\t\t \t\t\t\terror : function(xhr, error){\r\n");
      out.write("\t\t \t\t\t\t\tconsole.log(xhr.status);\r\n");
      out.write("\t\t \t\t\t\t\tconsole.log(error);\r\n");
      out.write("\t\t \t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t \t\t\t }); \r\n");
      out.write("\t\t            return\r\n");
      out.write("\t\t   }\r\n");
      out.write(" \t\t\t\r\n");
      out.write("  \r\n");
      out.write("\t    if(  $(\"#\"+i).find('i').hasClass('like') ) {\r\n");
      out.write("\t    \t$(\"#\"+i).find('i').removeClass('like');\r\n");
      out.write("\t    \t\r\n");
      out.write("\t \t\t$.ajax({\r\n");
      out.write("\t  \t\t\t\turl : '/nearby/board/likesCancel',\r\n");
      out.write("\t  \t\t\t\ttype: 'post',\r\n");
      out.write("\t  \t\t\t\tdata: \"bNo=\"+i, \r\n");
      out.write("\t \t\t\t\tdataType: 'json',\r\n");
      out.write("\t  \t\t\t\tsuccess: function(board){\r\n");
      out.write("\t  \t\t\t//\t  console.log(\"좋아요 취소 카운트\" + board.likes);\r\n");
      out.write("\t  \t\t\t\t   $( '#like_count'+ bNo ).text(board.likes);\r\n");
      out.write("\t  \t\t\t\t location.href=\"/nearby/board/selectBoard?bNo=\"+bNo;\r\n");
      out.write("\t  \t\t\t\t   \r\n");
      out.write("\t  \t\t\t\t},\r\n");
      out.write("\t  \t\t\t\terror : function(xhr, error){\r\n");
      out.write("\t  //\t\t\t\t\tconsole.log(xhr.error)\r\n");
      out.write("\t  \t\t\t\t}\t\t\t\t\r\n");
      out.write("\t  \t\t\t});  // ajax\r\n");
      out.write("\t  \t\t\treturn;\r\n");
      out.write("\t      } // if \r\n");
      out.write("\t    }\t \r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t/* ----------------------------------------- fnReplyList() --------------------------------  */\r\n");
      out.write("\tvar page = 1; // 시작은 무조건 1page이니까. 1로 초기화\r\n");
      out.write("\tfunction fnReplyList(){\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t      url: '/nearby/reply/replyList',\r\n");
      out.write("\t      type: 'get',\r\n");
      out.write("\t      data: \"bNo=\" + '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' + \"&page=\" + page,\r\n");
      out.write("\t      dataType: 'json',\r\n");
      out.write("\t      success: function(map) {\r\n");
      out.write("\t         fnReplyTotalCount(map);\r\n");
      out.write("\t         if (map.total != 0 ) {\r\n");
      out.write("\t\t         fnPrintPaging(map.pageUtils);\r\n");
      out.write("\t         } else if (map.total == 0) {\r\n");
      out.write("\t        \t $('#paging').empty();\r\n");
      out.write("\t         }\r\n");
      out.write("\t         fnPrintReplyList(map);\r\n");
      out.write("\t      },\r\n");
      out.write("\t      error: function(xhr) {\r\n");
      out.write("\t         console.log(xhr.responseText);\r\n");
      out.write("\t      }\r\n");
      out.write("\t   }) // End ajax\r\n");
      out.write("\t} // End fnReplyList\r\n");
      out.write("\r\n");
      out.write("\tfunction fnReplyTotalCount(map) {\r\n");
      out.write("\t         $('#reply_count_per_board').text(map.total);\r\n");
      out.write("\t         if (map.total > 0 ) {\r\n");
      out.write("\t            $('.replyCount').addClass('like').removeClass('unlike');\r\n");
      out.write("\t         } else if (map.total == 0) {\r\n");
      out.write("\t            $('.replyCount').addClass('unlike').removeClass('like');\r\n");
      out.write("\t         }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t   /* ----------------------------------------- fnPrintReplyList() --------------------------------  */\r\n");
      out.write("\r\n");
      out.write("\t\tfunction fnPrintReplyList(map){\r\n");
      out.write("\t\t\t $('.output_reply_table').empty();\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t var p = map.pageUtils;\r\n");
      out.write("\t\t\t let id = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t if (p.totalRecord == 0) {\r\n");
      out.write("\t\t\t    $('<tr>')\r\n");
      out.write("\t\t\t    .append( $('<td colspan=\"5\" class=\"reply_none\">').text('첫 번째 댓글의 주인공이 되어보세요!') )\r\n");
      out.write("\t\t\t    .appendTo( '.output_reply_table' );\r\n");
      out.write("\t\t\t } else {\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    $.each(map.replyList, function(i, reply){\r\n");
      out.write("\t\t\t         if ( reply.profile.pSaved != '' ) { // 댓글 작성자의 프로필 사진이 있을 때 프로필 사진을 보여주고\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\tlet pSaved = reply.profile.pSaved;\r\n");
      out.write("\t\t\t\t\t\t\tlet pPath = reply.profile.pPath;\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t\t\t\t\t$('.output_reply_table').append( $('<tr>').html( $('<td rowspan=\"2\" class=\"reply_user_image_area\"><img class=\"reply_user_img\" src=\"/nearby/'+pPath+'/'+pSaved+'\"></td>') ) );\r\n");
      out.write("\t\t\t           } else if(reply.profile.pPath == '') { // 댓글 작성자의 프로필 사진이 없을 때 디폴트 사진을 보여준다.\r\n");
      out.write("\t\t\t\t\t\t\t$('.output_reply_table').append( $('<tr>').html( $('<td rowspan=\"2\" class=\"reply_user_image_area\"><img class=\"reply_user_img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/profile_default.png\"></td>') ) );\r\n");
      out.write("\t\t\t           } // End if 프사 부분 \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('<tr class=\"icon_row\">')\r\n");
      out.write("\t\t\t\t\t.append( $('<td class=\"reply_user_name_area\">').html( $('<a id=\"link_'+reply.rNo+'\" class=\"user_page_link\">'+reply.id+'</a>') ) )\r\n");
      out.write("\t\t\t\t\t.append( $('<td class=\"like_icon_area\">') )\r\n");
      out.write("\t\t\t\t\t.append( $('<td class=\"btn_area\">').html( $('<input type=\"button\" class=\"show_reply_btn pointer disapear reply_btns\" data-upno=\"'+reply.rNo+'\" value=\"수정\" data-login=\"'+id+'\" data-writer=\"'+reply.id+'\"></td>') ) )\r\n");
      out.write("\t\t\t\t\t.append( $('<td class=\"btn_area\">').html( $('<input type=\"button\" class=\"delete_reply_btn pointer disapear reply_btns\" data-no=\"'+ reply.rNo +'\" value=\"삭제\" data-login=\"'+id+'\" data-writer=\"'+reply.id+'\" ></td>') ) )\r\n");
      out.write("\t\t\t\t\t.appendTo( '.output_reply_table' );\r\n");
      out.write("\t\t\t\t\t$('.output_reply_table').append( $('<tr class=\"input_row\">').html( $('<td colspan=\"4\"><input type=\"text\" class=\"reply_content\" id=\"updateContent\" value=\"'+reply.rContent+'\" readonly></td><td class=\"btn_area\"><input type=\"button\" class=\"update_reply_btn pointer reply_btns disapear reply_insert_btns\" data-updateno=\"'+reply.rNo+'\" value=\"등록\"></td>') ) );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 유저 이름당 href 링크 만들기\r\n");
      out.write("\t\t\t\t\tif (reply.id != id) {\r\n");
      out.write("\t\t\t\t\t\t$('.user_page_link[id=link_'+reply.rNo+']').attr('href','/nearby/board/selectUserHome?id='+reply.id);\r\n");
      out.write("\t\t\t\t\t} else if(reply.id == id) {\r\n");
      out.write("\t\t\t\t\t\t$('.user_page_link[id=link_'+reply.rNo+']').attr('href','/nearby/board/myHome');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t    }) // End each\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t$.each( $('.icon_row') , function(i, row) {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tlet update_btn = $($(this).find('.reply_btns')[0]);\r\n");
      out.write("\t\t\t\t\tlet delete_btn = $($(this).find('.reply_btns')[1]);\r\n");
      out.write("\t\t\t\t\tif (update_btn.data('login') == update_btn.data('writer')){\t\t\t\r\n");
      out.write("\t\t\t\t\t\tupdate_btn.removeClass('disapear');\r\n");
      out.write("\t\t\t\t\t\tdelete_btn.removeClass('disapear');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t } // End if \r\n");
      out.write("\t\t} // End fnPrintReplyList\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t/* ----------------------------------------- fnInsertReply() ----------------------------------------- */\r\n");
      out.write("\t\tfunction fnInsertReply(){\r\n");
      out.write("\t\t   $('#insert_reply_btn').on('click', function(){\r\n");
      out.write("\t\t\t   if ( $('#rContent').val().length > 40) {\r\n");
      out.write("\t\t\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t\t\ticon: 'warning',\r\n");
      out.write("\t\t\t\t\t\t\ttext: '댓글은 공백포함 40자 이내로 작성해주세요'\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t   return;\r\n");
      out.write("\t\t\t   } \r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t\t   if( $('#rContent').val().trim() == '' ) {\r\n");
      out.write("\t\t\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t\t\ticon: 'warning',\r\n");
      out.write("\t\t\t\t\t\t\ttext: '작성된 내용이 없습니다.'\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t   $('#rContent').focus();\r\n");
      out.write("\t\t\t\t   return;\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t      let reply = JSON.stringify({\r\n");
      out.write("\t\t         bNo: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\t         id: '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\r\n");
      out.write("\t\t         rContent: $('#rContent').val(),\r\n");
      out.write("\t\t         depth: 0,\r\n");
      out.write("\t\t         groupNo: 0,\r\n");
      out.write("\t\t         groupOrd: 0\r\n");
      out.write("\t\t      }); \r\n");
      out.write("\t\t      $.ajax({\r\n");
      out.write("\t\t         url: '/nearby/reply/insertReply',\r\n");
      out.write("\t\t         type: 'post',\r\n");
      out.write("\t\t         data: reply,\r\n");
      out.write("\t\t         contentType: 'application/json',\r\n");
      out.write("\t\t         dataType: 'json',\r\n");
      out.write("\t\t         success: function(map) {\r\n");
      out.write("\t\t               fnReplyList();\r\n");
      out.write("\t\t               if (map.errorMsg != null) {\r\n");
      out.write("\t\t\t   \t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t\t\t\ticon: 'warning',\r\n");
      out.write("\t\t\t\t\t\t\t\ttext: map.errorMsg\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t               } else {\r\n");
      out.write("\t\t\t               $('#rContent').val(''); // 나중에 주석 지워야 할 부분\r\n");
      out.write("\t\t               }\r\n");
      out.write("\r\n");
      out.write("\t\t         },\r\n");
      out.write("\t\t         error: function(xhr) {\r\n");
      out.write("\t\t            console.log(xhr.responseText);\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t      }) // End ajax\r\n");
      out.write("\t\t   }) // End click event\r\n");
      out.write("\t\t}  // End fnInsertReply\r\n");
      out.write("\t/* ----------------------------------------- fnDeleteReply() ----------------------------------------- */\r\n");
      out.write("\r\n");
      out.write("\tfunction fnDeleteReply(){\r\n");
      out.write("\t\t$('body').on('click', '.delete_reply_btn', function(){\r\n");
      out.write("\t\t\tlet deleteNo = $(this).data('no');\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: '/nearby/reply/deleteReply',\r\n");
      out.write("\t\t\t\t\ttype: 'get',\r\n");
      out.write("\t\t\t\t\tdata: 'rNo=' + deleteNo,\r\n");
      out.write("\t\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\t\t\tsuccess: function(map){\r\n");
      out.write("\t\t\t\t\t\tfnReplyList();\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(xhr){\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})// end ajax\r\n");
      out.write("\t\t})\r\n");
      out.write("\t} // end fnDeleteMember\r\n");
      out.write("/* ----------------------------------------- fnShowUpdateBtn() ----------------------------------------- */\r\n");
      out.write("\r\n");
      out.write("\tfunction fnShowUpdateBtn(){\r\n");
      out.write("\t\t$('body').on('click', '.show_reply_btn', function(){\r\n");
      out.write("\t\t\tlet upNo = $(this).data('upno');\r\n");
      out.write("\t\t\tlet content = $(this).parent().parent().next().children().find('input');\r\n");
      out.write("\t\t\tlet completeBtn = $(this).parent().parent().next().children().next().find('input');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcontent.removeAttr('readonly');\r\n");
      out.write("\t\t\tcompleteBtn.toggleClass('disapear');\r\n");
      out.write("\t\t}) // fnShowUpdateBtn\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("/* ----------------------------------------- fnUpdateReply() ----------------------------------------- */\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction fnUpdateReply(){\r\n");
      out.write("\t\t$('body').on('click', '.update_reply_btn', function(){\r\n");
      out.write("\t\t\tlet updateNo = $(this).data('updateno');\r\n");
      out.write("\t\t\tlet updateContent = $(this).parent().prev().find('input').val();\r\n");
      out.write("\t\t\tif ( updateContent.trim() == '') {\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'warning',\r\n");
      out.write("\t\t\t\t\ttext: '작성된 내용이 없습니다'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} else if (updateContent.length > 40) {\r\n");
      out.write("\t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\ticon: 'warning',\r\n");
      out.write("\t\t\t\t\ttext: '댓글은 공백포함 40자 이내로 작성해주세요'\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t          let reply = JSON.stringify({\r\n");
      out.write("\t              rNo : updateNo,\r\n");
      out.write("\t              rContent: updateContent\r\n");
      out.write("\t           });\r\n");
      out.write("\t\t\t \t$.ajax({\r\n");
      out.write("\t\t\t\t\turl: '/nearby/reply/updateReply',\r\n");
      out.write("\t\t\t\t\ttype: 'post',\r\n");
      out.write("\t\t\t\t\tcontentType: 'application/json',\r\n");
      out.write("\t\t\t\t\tdata: reply,\r\n");
      out.write("\t\t\t\t\tdataType: 'json',\r\n");
      out.write("\t\t\t\t\tsuccess: function(map){\r\n");
      out.write("\t\t\t\t\t\tfnReplyList();\r\n");
      out.write("\t\t\t               if (map.errorMsg != null) {\r\n");
      out.write("\t\t\t\t   \t\t\t\tSwal.fire({\r\n");
      out.write("\t\t\t\t\t\t\t\t\ticon: 'warning',\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttext: map.errorMsg\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t               }\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terror: function(){\r\n");
      out.write("\t\t\t\t\t\talert('응답 실패');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})// end ajax \r\n");
      out.write("\t\t})\r\n");
      out.write("\t} // end fnUpdateReply\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/* ----------------------------------------- fnPrintPaging() ----------------------------------------- */\r\n");
      out.write("\t// 페이징 출력 함수\r\n");
      out.write("\t\tfunction fnPrintPaging(p) {\r\n");
      out.write("\t\t\t$('#paging').empty();\r\n");
      out.write("\t\t   // 1페이지로 이동\r\n");
      out.write("\t\t\tif (page == 1) {\r\n");
      out.write("\t\t\t\t$('<div class=\"disable_link\">PREV</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('<div class=\"enable_link\" data-page=\"1\">PREV</div>').appendTo('#paging'); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 이전 블록으로 이동\r\n");
      out.write("\t\t\tif (page <= p.pagePerBlock) {\r\n");
      out.write("\t\t\t\t$('<div class=\"disable_link\">&nbsp;&nbsp;&nbsp;&lt;</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('<div class=\"enable_link\" data-page=\"'+(p.beginPage-1)+'\">&nbsp;&nbsp;&nbsp;&lt;</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 페이지 번호\r\n");
      out.write("\t\t\tfor (let i = p.beginPage; i <= p.endPage; i++) {\r\n");
      out.write("\t\t\t\tif (i == page) {\r\n");
      out.write("\t\t\t\t   $('<div class=\"disable_link now_page\">'+i+'</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t   $('<div class=\"enable_link\" data-page=\"'+i+'\">'+i+'</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// 다음블록으로 이동\r\n");
      out.write("\t\t\tif (p.endPage == p.totalPage) {\r\n");
      out.write("\t\t\t\t$('<div class=\"disable_link\">&gt;</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('<div class=\"enable_link\" data-page=\"'+(p.endPage+1)+'\">&gt;</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// 마지막 페이지로 이동\r\n");
      out.write("\t\t\tif (page == p.totalPage) {\r\n");
      out.write("\t\t\t\t$('<div class=\"disable_link\">NEXT</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('<div class=\"enable_link\" data-page=\"'+p.totalPage+'\">NEXT</div>').appendTo('#paging');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} // End fnPrintPaging\r\n");
      out.write("\r\n");
      out.write("\t/* ----------------------------------------- fnChangePage() ----------------------------------------- */\r\n");
      out.write("\t// 페이징 링크 처리 함수\r\n");
      out.write("\t\tfunction fnChangePage() {\r\n");
      out.write("\t\t\t$('body').on('click', '.enable_link', function(){\r\n");
      out.write("\t\t\t\tpage = $(this).data('page');\r\n");
      out.write("\t\t\t\tfnReplyList();\r\n");
      out.write("\t\t\t}) // body click event\r\n");
      out.write("\t\t} // End fnChangePage   \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"mainBoardWrap\" >\r\n");
      out.write("\t    <div class=\"boardIntro\"> \r\n");
      out.write("\t    \t<div class=\"profileImg\" id=\"p_img\">\r\n");
      out.write("\t    \t  ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t    \t<input type=\"hidden\" id=\"bNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t    \t<div class=\"idAndDate\">\t\r\n");
      out.write("\t\t    \t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    \t\t<div class=\"date\">\r\n");
      out.write("\t\t\t    \t    ");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t    \t    <i class=\"fas fa-globe-asia\" ></i>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t    \t</div> \r\n");
      out.write("\t    \r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t    \r\n");
      out.write("    \t<!-- 관리자일때만 삭제가능  아이콘 표시 -->\r\n");
      out.write("   \t\t");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t    \t\r\n");
      out.write("\t </div>\r\n");
      out.write("\t\t<!--------------------- 내용만 삽입할 때 ------------------------------->\r\n");
      out.write(" \t\t\t ");
      if (_jspx_meth_c_005fif_005f8(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("  \t\t<!-------------------- 이미지/비디오 삽입할때 ---------------->\t\t  \r\n");
      out.write("\t\t ");
      if (_jspx_meth_c_005fif_005f9(_jspx_page_context))
        return;
      out.write("\t\t\r\n");
      out.write("\t  \t\t<!--------------  댓글 + 좋아요 수 ----------------------->\r\n");
      out.write("\t  \t\t<div class=\"likesAndReplyCount\">\r\n");
      out.write("\t\t  \t\t<div class=\"countIcon likesCount\"> \r\n");
      out.write("\t\t  \t\t\t<span class=\"like_btn\" id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  data-bno=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" onclick=\"fnLike(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")\">\r\n");
      out.write("  \t\t\t \t    \t<i class=\"fas board_icon fa-thumbs-up\" id=\"like");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" > </i>\r\n");
      out.write("\t  \t\t\t\t\t<span class=\"like_count\"  id=\"like_count");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.likes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span> \r\n");
      out.write("  \t\t\t\t\t</span>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t\t\t  \t\t<div class=\"countIcon reply_count_box\">\r\n");
      out.write("\t\t\t  \t\t\t<i class=\"fas fa-comments countIcon replyCount\"></i>\r\n");
      out.write("\t\t  \t\t\t\t<span id=\"reply_count_per_board\">0</span>\r\n");
      out.write("\t\t\t  \t\t</div>\r\n");
      out.write("\t\t  \t\t</div>\r\n");
      out.write("\t \r\n");
      out.write("<!--  댓글 보이기  -->\r\n");
      out.write("\t<div class=\"input_reply_area\">\r\n");
      out.write("\t\t<!-- 댓글 작성 -->\r\n");
      out.write("\t\t<table id=\"input_reply_table\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f12(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f13(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"rContent\" id=\"rContent\" placeholder=\"댓글을 입력하세요\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td id=\"insert_btn_area\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" id=\"insert_reply_btn\" class=\"pointer reply_insert_btns\" value=\"등록\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div class=\"reply_wrap\">\r\n");
      out.write("\t\t<!-- 댓글 뿌리기 -->\r\n");
      out.write("  \t\t\t<div class=\"output_reply_area\">\r\n");
      out.write("\t  \t\t\t<table>\r\n");
      out.write("\t  \t\t\t\t<tbody class=\"output_reply_table\"></tbody>\r\n");
      out.write("\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"5\"><div id=\"paging\"></div></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tfoot>\r\n");
      out.write("\t  \t\t\t</table>\r\n");
      out.write("  \t\t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(486,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id != 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("      <header class=\"header\">\r\n");
          out.write("         ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/header.jsp", out, true);
          out.write("\r\n");
          out.write("      </header>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(492,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("      <header class=\"header\">\r\n");
          out.write("         ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layout/adminHeader.jsp", out, true);
          out.write("\r\n");
          out.write("      </header>\r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(501,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty board.profile.pSaved}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<img id=\"user_img\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/image/profile_default.png\" class=\"pointer defaultImg\">\r\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(504,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.profile.id == board.id and not empty board.profile.pSaved}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t    \t\t<img id=\"user_img\" src=\"/nearby/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.profile.pPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.profile.pSaved}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  class=\"pointer\">\r\n");
          out.write("\t\t    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(510,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id != board.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<a href=\"/nearby/board/selectUserHome?id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>                \r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(513,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id == board.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<a href=\"/nearby/board/myHome\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>                \r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(517,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.created}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/views/board/selectView.jsp(517,12) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("MM월 dd일  a hh:mm");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(522,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.id == loginUser.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("   \r\n");
          out.write("\t\t <div class=\"setting_wrap\">\t\r\n");
          out.write("\t    \t<i class=\"fas fa-ellipsis-h setting\" onclick=\"fnSetting()\"></i>\r\n");
          out.write("\t    \t<ul class=\"delete_update_form b_no\">\r\n");
          out.write("    \t\t\t<li class=\"update_link\" onclick=\"fnUpdate(); return false;\">게시글 수정</li>\r\n");
          out.write("\t    \t\t<li class=\"delete_link\" onclick=\"fnDelete(); return false; \">게시글 삭제</li>\r\n");
          out.write("\t\t    </ul>\r\n");
          out.write("\t\t   </div> \r\n");
          out.write("\t    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(533,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ 'admin' == loginUser.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("   \r\n");
          out.write("   \t\t <div class=\"setting_wrap\">\t\r\n");
          out.write("\t\t\t<i class=\"fas fa-ellipsis-h setting\" onclick=\"fnSetting()\"></i>\r\n");
          out.write("\t\t\t <ul class=\"delete_form b_no\">\r\n");
          out.write("\t\t\t   \t\t<li class=\"delete_link\" onclick=\"fnAdminDelete(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("); return false;\">게시글삭제</li>\r\n");
          out.write("\t  \t\t </ul>\r\n");
          out.write("  \t\t</div>\r\n");
          out.write("\t   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f8 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f8_reused = false;
    try {
      _jspx_th_c_005fif_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f8.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(544,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f8.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ null == board.origin }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f8 = _jspx_th_c_005fif_005f8.doStartTag();
      if (_jspx_eval_c_005fif_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t  \t\t\t<div class=\"AddrAndContent\"  onclick=\"location.href='/nearby/board/selectBoard?bNo=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("';\">\r\n");
          out.write("\t  \t\t\t\t  <div class=\"addrAndMap\">\r\n");
          out.write("\t\t\t\t\t\t       \t\t  <i class=\"fas fa-map-marker-alt\" style=\"color:#fe4662; font-size:15px; width:30px\"></i>\r\n");
          out.write("\t\t\t\t\t\t              <span class=\"address\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </span>\r\n");
          out.write("\t\t\t\t      </div>\r\n");
          out.write("\t\t       \t\t   <div class=\"content\">\r\n");
          out.write("\t\t       \t\t         <pre style='white-space:pre-wrap; word_wrap:break-word; word-break: break-all; width:505px;'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</pre>\r\n");
          out.write("\t\t       \t\t   </div>\r\n");
          out.write("\t  \t\t    </div>\r\n");
          out.write("\t\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f8.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f8);
      _jspx_th_c_005fif_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f9 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f9_reused = false;
    try {
      _jspx_th_c_005fif_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f9.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(556,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f9.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.saved ne null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f9 = _jspx_th_c_005fif_005f9.doStartTag();
      if (_jspx_eval_c_005fif_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t  \r\n");
          out.write("\t\t      <div class=\"addressAndImage\"  onclick=\"location.href='/nearby/board/selectBoard?bNo=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.bNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("';\">\r\n");
          out.write("\t\t\t      <div class=\"addrAndMap\">\r\n");
          out.write("\t\t\t       \t\t  <i class=\"fas fa-map-marker-alt\" style=\"color:#fe4662; font-size:15px; width:30px\"></i>\r\n");
          out.write("\t\t\t              <span class=\"address\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.location}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" </span>\r\n");
          out.write("\t\t\t      </div>\r\n");
          out.write("\t\t    \t  <!------------------ 이미지 및 영상 관련 ----------------------------------------->\r\n");
          out.write("  \t\t\t\t\t   ");
          if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f9, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t  \t\t\t\t ");
          if (_jspx_meth_c_005fif_005f10(_jspx_th_c_005fif_005f9, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t  \t\t\t\t\r\n");
          out.write("\t\t  \t\t\t\t");
          if (_jspx_meth_c_005fif_005f11(_jspx_th_c_005fif_005f9, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t  \t\t\t\t\t<input type=\"hidden\" name=\"path\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t  \t\t      <div class=\"content\">\r\n");
          out.write("\t\t       \t\t         <pre style='white-space:pre-wrap; word_wrap:break-word; word-break: break-all; width:499px;'>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</pre>\r\n");
          out.write("\t\t       \t\t   </div>\r\n");
          out.write("\t\t  \t\t</div>\r\n");
          out.write("\t\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f9.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f9);
      _jspx_th_c_005fif_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f9, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f9);
      // /WEB-INF/views/board/selectView.jsp(563,10) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/selectView.jsp(563,10) '${board.saved}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${board.saved}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/board/selectView.jsp(563,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("video");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f10(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f9, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f10 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f10_reused = false;
    try {
      _jspx_th_c_005fif_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f9);
      // /WEB-INF/views/board/selectView.jsp(564,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f10.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not f:contains(video, 'video')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fif_005f10 = _jspx_th_c_005fif_005f10.doStartTag();
      if (_jspx_eval_c_005fif_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t  \t\t\t\t\t\t <div class=\"imgSize\">  <img alt=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.origin}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" src=\"/nearby/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.saved}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"image\">  </div>\r\n");
          out.write("\t\t  \t\t\t\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f10.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f10);
      _jspx_th_c_005fif_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f11(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f9, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f11 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f11_reused = false;
    try {
      _jspx_th_c_005fif_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f9);
      // /WEB-INF/views/board/selectView.jsp(568,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f11.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f:contains(video, 'video')}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fif_005f11 = _jspx_th_c_005fif_005f11.doStartTag();
      if (_jspx_eval_c_005fif_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t  \t\t\t\t   <div class=\"imgSize\">\r\n");
          out.write("\t\t\t  \t\t\t\t    <video autoplay controls loop muted poster=\"video\"  id=\"video\">\r\n");
          out.write("\t\t\t  \t\t\t\t\t\t<source src=\"/nearby/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.saved}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  type=\"video/mp4\" >\r\n");
          out.write("\t\t\t  \t\t\t\t\t</video>\r\n");
          out.write("\t\t  \t\t\t\t\t</div>\r\n");
          out.write("\t\t  \t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f11.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f11);
      _jspx_th_c_005fif_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f11, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f12 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f12_reused = false;
    try {
      _jspx_th_c_005fif_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f12.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(601,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f12.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginUser.profile.pSaved}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f12 = _jspx_th_c_005fif_005f12.doStartTag();
      if (_jspx_eval_c_005fif_005f12 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<img class=\"reply_user_img\" src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/image/profile_default.png\" class=\"pointer defaultImg\">\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f12.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f12);
      _jspx_th_c_005fif_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f12, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f12_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f13 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f13_reused = false;
    try {
      _jspx_th_c_005fif_005f13.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f13.setParent(null);
      // /WEB-INF/views/board/selectView.jsp(604,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f13.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty loginUser.profile.pSaved}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f13 = _jspx_th_c_005fif_005f13.doStartTag();
      if (_jspx_eval_c_005fif_005f13 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<img class=\"reply_user_img\" src=\"/nearby/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.profile.pPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.profile.pSaved}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"pointer\">\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f13.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f13);
      _jspx_th_c_005fif_005f13_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f13, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f13_reused);
    }
    return false;
  }
}
