
DROP TABLE LIKES;
DROP TABLE REPLY;
DROP TABLE BOARD;
DROP TABLE FOLLOW;
DROP TABLE PROFILE;
DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    M_NO     INT  NOT NULL  AUTO_INCREMENT  NOT NULL PRIMARY KEY,
    ID       VARCHAR(32) NOT NULL UNIQUE,
    PW       VARCHAR(64) NOT NULL,
    NAME     VARCHAR(32) NOT NULL,
    EMAIL    VARCHAR(100) NOT NULL,
    BIRTHDAY VARCHAR(10) NOT NULL,
    PHONE    VARCHAR(12) NOT NULL,
    GENDER   VARCHAR(2) NOT NULL,
    STATE    INT,
    M_CREATED DATETIME,
    UNIQUE KEY(`ID`) 
);

CREATE TABLE BOARD (
    B_NO     INT AUTO_INCREMENT  NOT NULL PRIMARY KEY,
    ID       VARCHAR(32) NOT NULL,
    CONTENT  VARCHAR(4000),
    IP       VARCHAR(40),
    LOCATION VARCHAR(200),
    ORIGIN   VARCHAR(100),
    SAVED    VARCHAR(100),
    PATH     VARCHAR(200),
    LIKES    INT,
    CREATED  DATETIME NOT NULL,
    MODIFIED DATETIME NOT NULL,
    STATE    INT NOT NULL,
    DEPTH    INT,
    GROUPNO  INT,
    GROUPORD INT,
    FOREIGN KEY (`ID`) REFERENCES MEMBER(`ID`)
);


CREATE TABLE PROFILE (
    P_NO       INT AUTO_INCREMENT PRIMARY KEY,
    ID         VARCHAR(32)  NOT NULL,
    P_CONTENT   VARCHAR(1000),
    P_ORIGIN   VARCHAR(100),
    P_SAVED    VARCHAR(100),
    P_PATH     VARCHAR(200),
    FOREIGN KEY (`ID`) REFERENCES MEMBER(`ID`)
);

CREATE TABLE FOLLOW (
    F_NO      INT AUTO_INCREMENT PRIMARY KEY,
    FOLLOWING_ID VARCHAR(32) NOT NULL,
    FOLLOWED_ID  VARCHAR(32) NOT NULL,
     FOREIGN KEY (`FOLLOWING_ID`) REFERENCES PROFILE(`ID`),
     FOREIGN KEY (`FOLLOWED_ID`) REFERENCES PROFILE(`ID`),
     UNIQUE (`FOLLOWING_ID`, `FOLLOWED_ID`)
);



CREATE TABLE REPLY (
    R_NO      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID        VARCHAR(32) NOT NULL,
    B_NO      INT NOT NULL,
    R_CONTENT VARCHAR(1000) NOT NULL,
    R_LIKES   INT,
    R_CREATED DATETIME NOT NULL,
    R_MODIFIED DATETIME,
    STATE     INT,
    DEPTH     INT,
    GROUPNO   INT,
    GROUPORD  INT,
    FOREIGN KEY (`ID`) REFERENCES MEMBER(`ID`),
     FOREIGN KEY (`B_NO`) REFERENCES BOARD(`B_NO`)  
);

CREATE TABLE LIKES (
  LIKE_NO  INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  B_NO INT,
  ID VARCHAR(32),
  LIKE_CHECK INT,
  LIKE_DATE DATETIME,
   FOREIGN KEY (`ID`) REFERENCES MEMBER(`ID`),
   FOREIGN KEY (`B_NO`) REFERENCES BOARD(`B_NO`)
);