/*
	댓글형 게시판
	1. 공지사항 : notice
	2. 댓     글  : reply
*/

DROP TABLE REPLY;
DROP TABLE BOARD;

CREATE TABLE BOARD
(
/* 게시글 번호 */	NO				NUMBER,				
/* 작성자 이름 */	AUTHOR  		VARCHAR2(50),
/* 게시글 제목 */	TITLE			VARCHAR2(2000),
/* 게시글 내용 */	CONTENT 		VARCHAR2(4000),
/* 글의 조회수 */	HIT 			NUMBER,
/* 작성자 IP */	IP				VARCHAR2(32),
/* 최초 작성일 */	POSTDATE		DATE
);

CREATE TABLE REPLY
(
/* 댓글 번호    */	NO				NUMBER,
/* 댓글작성자  */	AUTHOR			VARCHAR2(50),
/* 댓글 내용    */	CONTENT			VARCHAR2(2000),
/* 작성자 IP */	IP				VARCHAR2(32),
/* 게시글 번호 */	BOARD_NO		NUMBER,
/* 최초 작성일 */	POSTDATE		DATE
);

ALTER TABLE BOARD ADD CONSTRAINT BOARD_PK PRIMARY KEY(NO);
ALTER TABLE REPLY ADD CONSTRAINT REPLY_PK PRIMARY KEY(NO);

ALTER TABLE REPLY ADD CONSTRAINT REPLY_BOARD_FK FOREIGN KEY(BOARD_NO) REFERENCES BOARD(NO) ON DELETE CASCADE;

DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE REPLY_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;
CREATE SEQUENCE REPLY_SEQ NOCACHE;



INSERT INTO BOARD 
VALUES (BOARD_SEQ.NEXTVAL, '관리자', '이용 시 주의사항', '바른말 사용하기', 0, '0:0:0:0:0:0:1', SYSDATE);

COMMIT









