DROP TABLE STUDENT;
CREATE TABLE STUDENT
(
	SNO			VARCHAR2(5) PRIMARY KEY,	-- 학번
	NAME		VARCHAR2(32),				-- 이름
	MIDTERM 	NUMBER,						-- 중간 점수
	FINALTERM	NUMBER,						-- 기말 점수
	PASS		VARCHAR2(1) 				-- 이수 여부
);


INSERT INTO STUDENT VALUES ('10101', '김가람', 87, 93, 'Y');
COMMIT