DROP TABLE MEMBER;
DROP TABLE BOARD_ATTACH;

CREATE TABLE MEMBER
(
    MEMBER_NO NUMBER PRIMARY KEY,
    ID VARCHAR2(100) NOT NULL UNIQUE,
    NAME VARCHAR2(100),
    GENDER VARCHAR2(3),
    ADDRESS VARCHAR2(100)
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ NOCACHE;

DROP TABLE BOARD;
CREATE TABLE BOARD
(
    BOARD_NO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENT VARCHAR2(100),
    WRITER VARCHAR2(100),
    IP VARCHAR2(40),
    CREATED DATE,
    LASTMODIFIED DATE
);

CREATE TABLE BOARD_ATTACH
(
    UUID VARCHAR2(32) PRIMARY KEY, 
    PATH VARCHAR2(300),
    ORIGIN VARCHAR2(300),
    FILETYPE VARCHAR2(1) DEFAULT 'I',
    BOARD_NO NUMBER REFERENCES BOARD (BOARD_NO)
);
-- 저장된 첨부파일명을 의미함 FILE NAME
-- 이미지를 기본값으로 설정 DEFAULT를 통해 기본 값을 부여할 수 있다.
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ NOCACHE;